apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2023-01-13T06:38:31Z"
  generation: 8
  name: monorepo-manifest
  namespace: openshift-gitops
  resourceVersion: "529623711"
  uid: 0c0e81a4-bb95-4295-9e77-99ce73fe4b63
spec:
  destination:
    server: https://kubernetes.default.svc
  project: workloads
  source:
    path: manifests/nginx
    repoURL: https://github.com/m4reshal/example-openshift-gitops
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
