apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multicluster-singleapp
  namespace: openshift-gitops
spec:
  generators:
  - clusters:
      selector:
        #matchLabels:
          #argocd.argoproj.io/secret-type: cluster
        matchExpressions:
          - key: usage
            operator: In
            values:
              - production
              - development
  template:
    metadata:
      name: 'nginx-deneme-{{name}}'
    spec:
      project: workloads
      syncPolicy:
        automated:
          #prune: true
          #selfHeal: true
          selfHeal: false
          prune: false
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/m4reshal/example-openshift-gitops
        targetRevision: master
        path: manifests/nginx
      destination:
        server: '{{server}}'
