apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multicluster-multiapp
  namespace: openshift-gitops
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              repoURL: https://github.com/m4reshal/example-openshift-gitops
              revision: master
              directories:
                - path: multicluster-apps/*
          # cluster generator, 'child' #2
          #- clusters: {}
          - clusters:
              selector:
                #matchLabels:
                  #argocd.argoproj.io/secret-type: cluster
                matchExpressions:
                  - key: usage
                    operator: In
                    values:
                      - production
                      - development
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      #name: '{{path.basename}}-{{metadata.labels.usage}}-{{name}}'
      name: '{{path.basename}}-{{name}}'
    spec:
      project: workloads
      syncPolicy:
        automated:
          #prune: true
          #selfHeal: true
          selfHeal: false
          prune: false
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/m4reshal/example-openshift-gitops
        targetRevision: master
        path: '{{path}}/envs/{{metadata.labels.usage}}'
      destination:
        server: '{{server}}'
